### ISSUE TITLE
Editing H5P content is slow

### ISSUE THREAD

**Issue by jgupta** [catalyst/moodle-tool_objectfs#308] opened 2020-05-06 16:36 UTC
Editing H5P content is very slow. We suspect it is caused by #306. #307 might be a solution.

We suspect editing is slow because files are being fetched from S3 and again being stored in S3 while saving H5P edits. I am not sure how this plugin works internally.

Could anyone give some insight on how should we debug and troubleshoot this to find the cause and possibly a solution?

**Comment by brendanheywood** [comment] 2020-05-07 02:48
This sounds like you have a lot of latency between you front ends and your s3. These should ideally be hosted in the same AZ so this sounds more like an infrastructure question than a code feature?

**Comment by jgupta** [comment] 2020-05-07 03:04
This deployment is on-premise and not on the cloud. We still want to use S3 and CloudFront for so many benefits that it brings but at the same time still want to use on-premise.

Average round trip latency is 13.506 ms. It is high compared to what one would get if they host within AWS but generally, 13ms isn't very high either.

**Comment by brendanheywood** [comment] 2020-05-07 03:09
Right ok, so yes then I think we should close this and focus on #306

**Closed** 2020-05-08 03:54 UTC

**Comment by brendanheywood** [comment] 2020-06-17 10:33
This might be of interest and should fix the root cause of the multiplied latency problem

https://tracker.moodle.org/browse/MDL-69057
