### ISSUE TITLE
Handling upload of files

### ISSUE THREAD

**Issue by zishanj** [catalyst/moodle-tool_objectfs#532] opened 2022-12-12 06:31 UTC
Is it possible to handle upload of files and store them on S3 instead of local storage? I think this plugin will just move objects from local storage to external based on some size criteria running in cron job.

**Comment by brendanheywood** [comment] 2022-12-12 07:33
hi @zishanj I'll close this as a duplicate of https://github.com/catalyst/moodle-tool_objectfs/issues/26

**Closed as completed by brendanheywood** 2022-12-12 07:33 UTC
Labels: duplicate
