### ISSUE TITLE
HELP Digitalocean space

### ISSUE THREAD

**Issue by juclopezso** [catalyst/moodle-tool_objectfs#416] opened 2021-04-17 22:03 UTC
Hello

I installed moodle version 3.10 on a DO droplet then I try to setup the objectfs plugin to store the files on a digitalocean space, but the files are not uploaded to the space. The Pre-Signed URL Test runs well, it uploads some files into the space but any other files are uploaded. I don't know if I missing something, this are my configs

`
enabletasks -> 1
maxtaskruntime -> 3600
enablelogging -> 0
useproxy -> 0
sizethreshold -> 10240
batchsize -> 10000
minimumage -> 600
deletelocal -> 0
consistencydelay -> 600
filesystem -> \tool_objectfs\digitalocean_file_system
preferexternal -> 0
do_key -> xxx
do_secret -> xxx
do_space -> xxx
do_region -> nyc3
proxyrangerequests -> 1
enablepresignedurls -> 0
expirationtime -> 7200
presignedminfilesize -> 0
signingwhitelist -> *
signingmethod -> s3
`

**Comment by guillefd** [comment] 2021-04-18 11:57
Not sure if it works on v3.10, but it does work ok on 3.9.
There was some missing settings on client.php file that may need to be added manually, check here https://github.com/catalyst/moodle-tool_objectfs/pull/323/commits/4649715474370911228541043bb720e33307735e

**Comment by danmarsden** [comment] 2021-04-18 21:49
Hi @juclopezso - also make sure you have cron running - the task to move content from local to object storage relies on the cron.

We're not really in a position to provide free "Help" configuring your site - best place to ask for "help" like this is in the community forums on moodle.org - I'm closing this as "not a bug" - but feel free to open a new issue if further investigation on your end identifies an issue with our digitalocean implementation.

If you would like commercial level support feel free to reach out to us via the contact form on the Catalyst IT site.

Good luck!

**Closed by danmarsden** 2021-04-18 21:49 UTC
