### ISSUE TITLE
Not all AWS S3 regions supported

### ISSUE THREAD

**Issue by uni4online** [catalyst/moodle-tool_objectfs#314] opened 2020-05-08 15:17 UTC
I have a bucket in af-south-1 which I would like to store my course data in but the region is not supported. Even If I add it in the DB the settings UI still tries to use one of the supported regions.

**Comment by brendanheywood** [comment] 2020-05-11 08:30
+1 I've been meaning to get that logic moved into local_aws so it's dynamic and shared across the suite of aws plugins

See https://github.com/catalyst/moodle-local_aws/issues/13

**Comment by brendanheywood** [comment] 2020-05-11 08:32
closing as duplicate of https://github.com/catalyst/moodle-tool_objectfs/issues/146

**Closed by brendanheywood** 2020-05-11 08:32 UTC
